name: "Nanobot AI"
description: "Ultra-Lightweight AI Agent for Home Assistant. Supports MCP, Telegram & Custom Skills."
version: "0.5.1"
slug: "nanobot"
init: false
arch:
  - amd64
map:
  - share:rw

options:
  workspace_path: "/share/nanobot_workspace"
  restrict_to_workspace: true
  provider: "openrouter"
  api_key: ""
  api_base: ""
  model: "deepseek/deepseek-r1"
  fallback_enabled: false
  fallback_provider: "openai"
  fallback_api_key: ""
  fallback_model: "openai/gpt-4o-mini"
  telegram_enabled: true
  telegram_token: ""
  telegram_allow_user: ""

schema:
  workspace_path: str
  restrict_to_workspace: bool
  provider: str
  api_key: password
  api_base: str?
  model: str
  fallback_enabled: bool
  fallback_provider: str?
  fallback_api_key: password?
  fallback_model: str?
  telegram_enabled: bool
  telegram_token: password?
  telegram_allow_user: str?
